#!/usr/bin/bash
# -*- sh -*-

. "$MUNIN_LIBDIR/plugins/plugin.sh"

myname=$(basename "$0" | sed 's/^ps_//g')

name="${name-\<$myname\>}"
REGEX="${regex-\<$name\>}"

if [ "$1" = "config" ]; then

        echo "graph_title Number of $myname processes"
        echo 'graph_args --base 1000 --vertical-label processes -l 0'
        echo 'graph_category processes'
        echo "count.label $myname"
        print_warning count
        print_critical count
        exit 0
fi

printf "count.value "

/usr/bin/pgrep -f -l "$name" | grep -v grep | wc -l